# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
env:
  PRE_BUILD_COMMAND: git config --global --add safe.directory /github/workspace
  
name: pmd

on:
  push:
    branches: [ "master" ]
   
  pull_request:
    branches: [ "master" ]
    
  schedule:
    - cron: '40 1 * * 0'

permissions:
  contents: read
  
jobs:
  
          
  build_maven:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install

  visualize_code_coverage:
    needs: build_maven

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Copy Jacoco report
        run: cp -r VIP-portal/coverage/target/site/jacoco-aggregate/ public

      - name: Publish Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage Report
          path: public    
          
  
      
          
