# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
env:
  PRE_BUILD_COMMAND: git config --global --add safe.directory /github/workspace
  
name: pmd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '40 1 * * 0'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'ruleset.xml'
          analyzeModifiedFilesOnly: false
                              
      - name: Create results
        run: |
              mkdir -m 777 -p results
              ls -la results              
              cp -r pmd-report.sarif results
              echo "Artifacts pushed to results"
              

      - name: Push Artifacts
        run: |
              git config --global user.name "virtual-imaging-platform"
              git config --global user.email "mathilde.marza@insa-lyon.fr"
              git add results
              git commit -m "Push results folder"
              git push

          
      - name: Generate Security Report
        uses: peter-murray/github-security-report-action@v2
        with:
          token: ${{secrets.SECURITY_TOKEN}}
          repository: MathildeMrz/vip-portal
          sarifReportDir:  results
          
