# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
env:
  PRE_BUILD_COMMAND: git config --global --add safe.directory /github/workspace
  
name: pmd

on:
  push:
    branches: [ "master" ]
   
  pull_request:
    branches: [ "master" ]
    
  schedule:
    - cron: '40 1 * * 0'

permissions:
  contents: read
  
jobs:
  
          
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: qcastel/github-actions-maven/actions/maven@master
        with:
          maven-repo-server-id: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
          maven-repo-server-username: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
          maven-repo-server-password: ${{ secrets.MVN_REPO_PRIVATE_REPO_PASSWORD }}
          maven-args: "clean install"
          
      - name: Upload site to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site
          # La tâche ne sera pas exécutée si aucun fichier n'est généré
          if-no-files-found: error

  deploy:
    name: Deploy
    # La tâche 'deploy' est exécutée après la tâche 'build'
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download site from Artifacts
      uses: actions/download-artifact@v2
      with:
        name: _site
        path: _site

    - name: Deploy site to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        # Accès en écriture à la branche cible (`gh-pages`)
        GITHUB_TOKEN: ${{ secrets.SECURITY_TOKEN }}
      with:
        # Adresse e-mail valide sur GitHub
        email: mathilde.marza@insa-lyon.fr

  
  
      
          
