# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '40 1 * * 0'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'ruleset.xml'
          analyzeModifiedFilesOnly: false
                              
      - name: Create results
        run: |
              ls -la results
              mkdir -p results
              cp -r pmd-report.sarif results
              echo "Artifacts pushed to results"

      - name: Push Artifacts
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: master
          github_token: ${{secrets.SECURITY_TOKEN}}
          force: true
          directory: results
          
      - name: Generate Security Report
        uses: peter-murray/github-security-report-action@v2
        with:
          token: ${{secrets.SECURITY_TOKEN}}
          repository: MathildeMrz/vip-portal
          sarifReportDir:  results
          
